### ISSUE TITLE
ToDos

### ISSUE THREAD

**Issue by floydsteam** [maxbachmann-university/BlindControl#13]
- [x] ESP32 programmieren
- [x] NRF Software
- [x] Raspberry konfigurieren
- [ ] Doku schreiben

**Comment by floydsteam** [comment]
### ToDos für die Doku

- [ ] Problembeschreibung + Lösung
- [ ] Anforderungen
- Tabelle
- UseCase Diagram
- [ ] Planung
- Arbeitspakete
- Zeitplan
- Kosten
- [ ] Architektur
- Statistische Architektur
-Component Diagram
- Verhalten
-State or Activity Diagram
- [ ] Implementierung
- Interessante Code-Segmente
- Gegenüberstellung Komplexität (SLOC)
-1. Schätzung, 2. Schätzung, Lösung
- [ ] Test
- Test Procedure/Report
- Ggf. Deployment Diagram
- [ ] Installationsanleitung
- Deployment Diagram
- [ ] Benutzerhandbuch

**Comment by maxbachmann** [comment]
Ich denke es mach Sinn wenn ich was zur Implementierung und Test schreibe, da ihr damit ja nicht wirklich groß was zu tun hattet

**Comment by floydsteam** [comment]
@maxbachmann Ja, passt ;-)

**Comment by floydsteam** [comment]
Hab jetzt mal den Branch "Latex_Doku" erstellt und die Latex Doku mit den oben genannten Kapiteln angelegt. Die kann man dann ja, wie man will, umbenennen.
